fix build warnings in terraware-web related to typescript version
- warning is
```
TypeError: Cannot set property mark of #<Object> which has only a getter
TypeError: Cannot set property mark of #<Object> which has only a getter
    at Object.connectTypeScriptPerformance
```
- fix offending package version
- see https://github.com/TypeStrong/fork-ts-checker-webpack-plugin/issues/797